"""add parent_id to food_entries

Revision ID: 0539d7244100
Revises: 001
Create Date: 2026-01-18 21:24:48.365528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0539d7244100'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_entries', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_food_entries_parent_id'), 'food_entries', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'food_entries', 'food_entries', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food_entries', type_='foreignkey')
    op.drop_index(op.f('ix_food_entries_parent_id'), table_name='food_entries')
    op.drop_column('food_entries', 'parent_id')
    # ### end Alembic commands ###
